In [1]:
import numpy as np

In [2]:
num_qubit=3

In [3]:
tableau = np.zeros((2*num_qubit, 2*num_qubit+1), dtype=int) 

In [4]:
tableau

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [5]:
import numpy as np

# Dimensions
n = 3  # Example size
rows, cols = 2 * n, 2 * n + 1

# Create an array of the specified shape
A = np.zeros((rows, cols))

# Create indices for the diagonal
diagonal_indices = np.arange(min(rows, cols))

# Set the diagonal elements to 1
A[diagonal_indices, diagonal_indices] = 1

print(A)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]


In [6]:
diagonal_indices

array([0, 1, 2, 3, 4, 5])